### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shijunil** [klintan/py-nltk-svo#1]
I m getting following error

NLTK was unable to find stanford-parser.jar! Set the CLASSPATH
  environment variable.

I tried setting the classpath by giving the path to the stanford parser.jar but I m still getting following error
NLTK was unable to find stanford-parser-(\d+)(.(\d+))+-models.jar!
  Set the CLASSPATH environment variable.

**Comment by klintan** [comment]
Hi, will look into it and see if I can provide an example in the readme.

**Comment by klintan** [comment]
Try giving the full absolute path to the classpaths of both the models and parser in the python file.
Try to get Stanford Parser to work with an example in NLTK. 

I removed the empty quotes to the model file in the SVO-script. Will close this issue since it is related to getting NLTK Stanford to work rather than the script itself.
